version: '3.8'
services:
  notificationservice:
    build: .
    ports:
      - "5004:80"
    env_file:
      - ./local.env
    environment:
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

