// <auto-generated />
using System;
using LoanService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanService.Migrations
{
    [DbContext(typeof(loandbcontext))]
    partial class loandbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanService.Models.Entities.loanaction", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("actiontype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actiontype");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("loanid")
                        .HasColumnType("uuid")
                        .HasColumnName("loanid");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("id")
                        .HasName("pk_loanaction");

                    b.ToTable("loanaction", (string)null);
                });

            modelBuilder.Entity("LoanService.Models.Entities.loanagreement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filepath");

                    b.Property<bool>("issigned")
                        .HasColumnType("boolean")
                        .HasColumnName("issigned");

                    b.Property<Guid>("loanid")
                        .HasColumnType("uuid")
                        .HasColumnName("loanid");

                    b.Property<DateTime?>("signedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signedat");

                    b.HasKey("id")
                        .HasName("pk_loanagreement");

                    b.ToTable("loanagreement", (string)null);
                });

            modelBuilder.Entity("LoanService.Models.Entities.loaninterest", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("effectivefrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<decimal>("rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("id")
                        .HasName("pk_loaninterest");

                    b.ToTable("loaninterest", (string)null);
                });

            modelBuilder.Entity("LoanService.Models.Entities.loans", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("customerid")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<decimal>("interestrate")
                        .HasColumnType("numeric")
                        .HasColumnName("interestrate");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("termmonths")
                        .HasColumnType("integer")
                        .HasColumnName("termmonths");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("id")
                        .HasName("pk_loans");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("LoanService.Models.Entities.penaltyinterest", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("dailyrate")
                        .HasColumnType("numeric")
                        .HasColumnName("dailyrate");

                    b.Property<DateTime>("effectivefrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<int>("graceperioddays")
                        .HasColumnType("integer")
                        .HasColumnName("graceperioddays");

                    b.HasKey("id")
                        .HasName("pk_penaltyinterest");

                    b.ToTable("penaltyinterest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
