// <auto-generated />
using System;
using CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(customerdbcontext))]
    partial class customerdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Models.Entities.customeraddress", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("customerid")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<string>("line1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line1");

                    b.Property<string>("line2")
                        .HasColumnType("text")
                        .HasColumnName("line2");

                    b.Property<string>("postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("id")
                        .HasName("pk_customeraddress");

                    b.ToTable("customeraddress", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.Entities.customerbank", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("accountholdername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accountholdername");

                    b.Property<string>("accountnumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accountnumber");

                    b.Property<string>("bankname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bankname");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("customerid")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<string>("sortcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sortcode");

                    b.HasKey("id")
                        .HasName("pk_customerbank");

                    b.ToTable("customerbank", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.Entities.customerdebt", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("customerid")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<string>("debttype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debttype");

                    b.HasKey("id")
                        .HasName("pk_customerdebt");

                    b.ToTable("customerdebt", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.Entities.customeremployment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("customerid")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<string>("employmentstatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employmentstatus");

                    b.Property<string>("incomesource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incomesource");

                    b.Property<decimal>("monthlyincome")
                        .HasColumnType("numeric")
                        .HasColumnName("monthlyincome");

                    b.HasKey("id")
                        .HasName("pk_customeremployment");

                    b.ToTable("customeremployment", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.Entities.customers", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("dateofbirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<Guid>("userid")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
